### ISSUE TITLE
CS / CF Folder

### ISSUE THREAD

**Issue by yanhamu** [Sitecore/Reference-Storefront#12]
What is the difference between CS and CF subfolders in this repo and what is purpose of CS and CF?

Default Commerce.Server.Storefront.sln file is pointing to CS/* projects, and I can only use CF. (When I use CS, sitecore will end up with "invalid type" errors, however I need to use Shipping Processors from CS that are not present in CF)

**Comment by davidhargis** [comment]
CS is the storefront that uses the "Commerce Server" product for all commerce services.  CF uses the new "Sitecore Commerce Engine".  To open the CF storefront in Visual Studio, use the Commerce.Engine.Storefront.sln solution.
