### ISSUE TITLE
8.1.x releases no longer have pup packages. Not needed?

### ISSUE THREAD

**Issue by pveller** [Sitecore/Reference-Storefront#5]
I am following an installation guide that my team left behind and they refer to the `pup` packages. I couldn't find them in the most recent storefront downloads but I do see them in 1.1. Is it no longer needed? If it is, where I can get it, can you guys tell me please? Thanks!

**Comment by larrelandin** [comment]
As of Sitecore Commerce Server 8.1, PUP-packages are no longer needed. Instead there is a collection of PowerShell CmdLets to help you setup and configure Commerce Server.
Read more here: http://commercesdn.sitecore.net/SCpbCS81/SitecoreCommerceDeploymentGuide/en-us/index.html#c_SetupCS_Site_PowerShell.html

**Comment by pveller** [comment]
Thank you @larrelandin, makes sense!
